branch-defaults:
  production/core:
    environment: prod-world88
environment-defaults:
  prod-world88:
    branch: null
    repository: null
global:
  application_name: world88.com
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
