export const MODAL_HEADER = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  DEPOSIT_WITHDRAW: 'DEPOSIT_WITHDRAW',
  INFO: 'INFO',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  HISTORY: 'HISTORY',
  LOG_OUT: 'LOG_OUT',
  SIGN_IN: 'SIGN_IN',
};
