export const GAME_CATEGORY = {
  UFA: 'UFA',
  SLOT: 'SLOT',
  SPORT_BOOK: 'SPORT_BOOK',
  LIVE_CASINO: 'LIVE_CASINO',
  FISHING_GAMES: 'FISHING_GAMES',
  TABLE_GAMES: 'TABLE_GAMES',
  ARCADE: 'ARCADE',
  LOTTO: 'LOTTO',
  OTHER: 'OTHER',
};
