export const PROMOTION_TPYE = {
  CASHBACK: 'CASHBACK',
  FREE_CREDIT: 'FREE_CREDIT',
  FIRST_DEPOSIT: 'FIRST_DEPOSIT',
  NEW_REGISTER: 'NEW_REGISTER',
  CUSTOM: 'CUSTOM'
};

export const MULTIPLY_TYPE = {
  FIAT: 'FIAT',
  PERCENTAGE: 'PERCENTAGE',
};

export const WITHDRAW_TYPE = {
  TURNOVER: 'TURNOVER',
  WINLOSE: 'WINLOSE',
};
